import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="">
            <nav className="  w-screen text-white py-4 px-10 border-b-2 border-slate-700  bg-slate-800 ">
              <div className="w-full flex justify-between items-center px-10">
                <h2 className="font-bold  text-slate-50 text-3xl tracking-tighter  ">
                  PDFRAG
                </h2>
                <div className="flex gap-4">
                  <SignedOut>
                    <SignInButton>
                      <button className="text-slate-950 px-2 py-1 rounded-lg font-semibold bg-slate-50 border-2 hover:shadow hover:shadow-white hover:text-slate-500 transition-all duration-300 delay-100">
                        SignIn
                      </button>
                    </SignInButton>

                    <SignUpButton>
                      <button className="text-slate-950 px-2 py-1 rounded-lg font-semibold bg-slate-50 border-2 hover:shadow hover:shadow-white hover:text-slate-500 transition-all duration-300 delay-100 ">
                        SignUp
                      </button>
                    </SignUpButton>
                  </SignedOut>
                  <SignedIn>
                    <UserButton />
                  </SignedIn>
                </div>
              </div>
            </nav>
          </header>

          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
